# -*- coding: utf-8 -*-
"""speech .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTfRYOmEYp8pqSV3hIf0MvhmgLROXw8-
"""

# List of offensive words
offensive_words = [
    "inyenzi", "cockroaches", "kill", "exterminate", "destroy",
    "traitors", "snakes", "rats", "hutu power", "tutsi",
    "ethnic cleansing", "wipe out", "enemy", "revenge",
    "impurity", "traitors", "infiltrators", "parasites"
]

# Function to detect hate speech
def detect_hate_speech(speech):
    detected_words = [word for word in offensive_words if word in text.lower()]
    return detected_words

# Example usage
speech = "The Tutsis are like cockroaches, they must be exterminated, they must be killed, and we, the Hutus, will be the ones to do it. We must carry out our revolution, and the revolution is to eliminate the Tutsi. If we do not kill them, they will kill us. There are no more excuses. We must be like the grasshoppers and finish off the cockroaches. We must get rid of them.”"
hate_words = detect_hate_speech(speech)
if hate_words:
    print("Hate speech detected! Offensive words:", hate_words)
else:
    print("No hate speech detected.")
    print("No hate speech detected.")