# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13t4tQx7TjI1396ik8QG27WcrWXbpvKu-
"""

import pandas as pd
phishing_keywords = ["urgent", "password reset", "bank", "verify", "account suspended"]

emails = pd.read_csv("/content/2401001428.csv")
if 'Content' in emails.columns:
  emails['is_phishing'] = emails['Content'].apply(
      lambda x: any(keyword in str(x).lower() for keyword in phishing_keywords)
  )
  emails.to_csv("/content/2401001428_phishing.csv", index=False)
  print("Phishing detection complete. ✅")
else:
  print("Error: The 'content' column is missing from the dataset.")